# 6.1 Cleaning and Descriptive Statistics

## Contents List:

- Import libraries and cause_of_deaths_raw_data.csv

- Check for missing values

- Check for duplicates

- Check for mixed-type data

- List data types

- Perform basic descriptive statistics

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# Import cause_of_deaths_raw_data.csv

path = r'C:\Users\susan\OneDrive\Desktop\Data Analytics Program'

df_deaths_raw = pd.read_csv(os.path.join(path, 'cause_of_deaths_raw_data.csv'), index_col = False)

In [23]:
# Set the max columns to none

pd.set_option('display.max_columns', None)

In [24]:
# Check structure

df_deaths_raw.head()

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,Maternal Disorders,HIV/AIDS,Drug Use Disorders,Tuberculosis,Cardiovascular Diseases,Lower Respiratory Infections,Neonatal Disorders,Alcohol Use Disorders,Self-harm,Exposure to Forces of Nature,Diarrheal Diseases,Environmental Heat and Cold Exposure,Neoplasms,Conflict and Terrorism,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,2655,34,93,4661,44899,23741,15612,72,696,0,4235,175,11580,1490,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,2885,41,102,4743,45492,24504,17128,75,751,1347,4927,113,11796,3370,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,3315,48,118,4976,46557,27404,20060,80,855,614,6123,38,12218,4344,2153,3776,386,2404,5106,6223,2830,5335,360,3325
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,3671,56,132,5254,47951,31116,22335,85,943,225,8174,41,12634,4096,2195,3862,425,2797,5681,6445,2943,5568,396,3601
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,3863,63,142,5470,49308,33390,23288,88,993,160,8215,44,12914,8959,2231,3932,451,3038,6001,6664,3027,5739,420,3816

In [7]:
# Check shape

df_deaths_raw.shape

(6120, 34)

## Check for missing values

In [8]:
df_deaths_raw.isnull().sum()

Country/Territory                             0
Code                                          0
Year                                          0
Meningitis                                    0
Alzheimer's Disease and Other Dementias       0
Parkinson's Disease                           0
Nutritional Deficiencies                      0
Malaria                                       0
Drowning                                      0
Interpersonal Violence                        0
Maternal Disorders                            0
HIV/AIDS                                      0
Drug Use Disorders                            0
Tuberculosis                                  0
Cardiovascular Diseases                       0
Lower Respiratory Infections                  0
Neonatal Disorders                            0
Alcohol Use Disorders                         0
Self-harm                                     0
Exposure to Forces of Nature                  0
Diarrheal Diseases                            0
Environmental Heat and Cold Exposure          0
Neoplasms                                     0
Conflict and Terrorism                        0
Diabetes Mellitus                             0
Chronic Kidney Disease                        0
Poisonings                                    0
Protein-Energy Malnutrition                   0
Road Injuries                                 0
Chronic Respiratory Diseases                  0
Cirrhosis and Other Chronic Liver Diseases    0
Digestive Diseases                            0
Fire, Heat, and Hot Substances                0
Acute Hepatitis                               0
dtype: int64

### There are 0 missing values in the dataset.

## Check for duplicates

In [9]:
# look for full duplicates

df_dups = df_deaths_raw[df_deaths_raw.duplicated()]

In [25]:
df_dups

Empty DataFrame
Columns: [Country/Territory, Code, Year, Meningitis, Alzheimer's Disease and Other Dementias, Parkinson's Disease, Nutritional Deficiencies, Malaria, Drowning, Interpersonal Violence, Maternal Disorders, HIV/AIDS, Drug Use Disorders, Tuberculosis, Cardiovascular Diseases, Lower Respiratory Infections, Neonatal Disorders, Alcohol Use Disorders, Self-harm, Exposure to Forces of Nature, Diarrheal Diseases, Environmental Heat and Cold Exposure, Neoplasms, Conflict and Terrorism, Diabetes Mellitus, Chronic Kidney Disease, Poisonings, Protein-Energy Malnutrition, Road Injuries, Chronic Respiratory Diseases, Cirrhosis and Other Chronic Liver Diseases, Digestive Diseases, Fire, Heat, and Hot Substances, Acute Hepatitis]
Index: []

### There are no duplicates in this dataset.

## Check for mixed-type data

In [11]:
for col in df_deaths_raw.columns.tolist():
  weird = (df_deaths_raw[[col]].applymap(type) != df_deaths_raw[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_deaths_raw[weird]) > 0:
    print (col)

### There is no mixed-type data in this dataset.

## List data types

In [18]:
df_deaths_raw.dtypes

Country/Territory                             object
Code                                          object
Year                                           int64
Meningitis                                     int64
Alzheimer's Disease and Other Dementias        int64
Parkinson's Disease                            int64
Nutritional Deficiencies                       int64
Malaria                                        int64
Drowning                                       int64
Interpersonal Violence                         int64
Maternal Disorders                             int64
HIV/AIDS                                       int64
Drug Use Disorders                             int64
Tuberculosis                                   int64
Cardiovascular Diseases                        int64
Lower Respiratory Infections                   int64
Neonatal Disorders                             int64
Alcohol Use Disorders                          int64
Self-harm                                      int64
Exposure to Forces of Nature                   int64
Diarrheal Diseases                             int64
Environmental Heat and Cold Exposure           int64
Neoplasms                                      int64
Conflict and Terrorism                         int64
Diabetes Mellitus                              int64
Chronic Kidney Disease                         int64
Poisonings                                     int64
Protein-Energy Malnutrition                    int64
Road Injuries                                  int64
Chronic Respiratory Diseases                   int64
Cirrhosis and Other Chronic Liver Diseases     int64
Digestive Diseases                             int64
Fire, Heat, and Hot Substances                 int64
Acute Hepatitis                                int64
dtype: object

### There are 2 columns with object data types and 32 columns with int64 data types.

## Perform basic descriptive statistics

In [26]:
df_deaths_raw.describe()

,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,Maternal Disorders,HIV/AIDS,Drug Use Disorders,Tuberculosis,Cardiovascular Diseases,Lower Respiratory Infections,Neonatal Disorders,Alcohol Use Disorders,Self-harm,Exposure to Forces of Nature,Diarrheal Diseases,Environmental Heat and Cold Exposure,Neoplasms,Conflict and Terrorism,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
count,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6.120000e+03,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6.120000e+03,6120.000000,6.120000e+03,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6.120000e+03,6120.000000,6120.000000,6120.000000,6120.000000
mean,2004.500000,1719.701307,4864.189379,1173.169118,2253.600000,4140.960131,1683.333170,2083.797222,1262.589216,5941.898529,434.006699,7491.928595,7.316045e+04,13687.914706,12558.942647,787.421242,3874.825327,243.485621,1.082280e+04,292.295915,3.754224e+04,538.243954,5138.704575,4724.132680,425.013399,1965.994281,5930.795588,1.709237e+04,6124.072059,10725.267157,588.711438,618.429902
std,8.656149,6672.006930,18220.659072,4616.156238,10483.633601,18427.753137,8877.018366,6917.006075,6057.973183,21011.962487,2898.761628,39549.977578,2.915775e+05,48031.720009,56058.366412,3545.823616,18425.616418,4717.104377,6.541617e+04,1704.466356,1.615584e+05,7033.308187,16773.081040,16470.429969,2022.640521,8255.999063,24097.784291,1.051572e+05,20688.118580,37228.051096,2128.595120,4186.023497
min,1990.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,1997.000000,15.000000,90.000000,27.000000,9.000000,0.000000,34.000000,40.000000,5.000000,11.000000,3.000000,35.000000,2.028000e+03,345.000000,131.000000,9.000000,94.000000,0.000000,2.000000e+01,2.000000,8.097500e+02,0.000000,236.000000,145.750000,6.000000,5.000000,174.750000,2.890000e+02,154.000000,284.000000,17.000000,2.000000
50%,2004.500000,109.000000,666.500000,164.000000,119.000000,0.000000,177.000000,265.000000,54.000000,136.000000,20.000000,417.000000,1.174200e+04,2126.500000,916.000000,80.000000,533.000000,0.000000,2.965000e+02,21.000000,5.629500e+03,0.000000,1087.000000,822.000000,52.500000,92.000000,966.500000,1.689000e+03,1210.000000,2185.000000,126.000000,15.000000
75%,2012.000000,847.250000,2456.250000,609.250000,1167.250000,393.000000,698.000000,877.000000,734.000000,1879.000000,129.000000,2924.250000,4.254650e+04,10161.250000,7419.750000,316.000000,1882.250000,12.000000,3.946750e+03,109.000000,2.014775e+04,23.000000,2954.000000,2922.500000,254.000000,1042.500000,3435.250000,5.249750e+03,3547.250000,6080.000000,450.000000,160.000000
max,2019.000000,98358.000000,320715.000000,76990.000000,268223.000000,280604.000000,153773.000000,69640.000000,107929.000000,305491.000000,65717.000000,657515.000000,4.584273e+06,690913.000000,852761.000000,55200.000000,220357.000000,222641.000000,1.119477e+06,29048.000000,2.716551e+06,503532.000000,273089.000000,222922.000000,30883.000000,202241.000000,329237.000000,1.366039e+06,270037.000000,464914.000000,25876.000000,64305.000000

### Cardiovascular Diseases (73,160) and Neoplasms (37,542) have the highest mean values by far. It is interesting to note that for almost all of the causes of death, the minimum is 0.